---
# **Vector and matrix transpose**
---

## Import

In [21]:
import torch
torch. __version__

'1.8.1'

In [22]:
import numpy as np

## Numpy

In [23]:
nv = np.array([[1, 2, 3]])

nvT = nv.T

In [24]:
print(nv, end='\n\n')
print(nvT, end='\n\n')
print(nvT.T, end='\n\n')

[[1 2 3]]

[[1]
 [2]
 [3]]

[[1 2 3]]



In [25]:
nM = np.array([[1, 2, 3], [4, 5, 6]])

nMT = nM.T

In [26]:
print(nM, end='\n\n')
print(nMT, end='\n\n')
print(nMT.T, end='\n\n')

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 2 3]
 [4 5 6]]



## Pytorch