---
# ***If-else statements, part 1***
---

In [9]:
if True:
    print('This is true')

This is true


In [10]:
x = 4

if x == 4:
    print('Value is 4')

Value is 4


In [12]:
if 'kavinda':
    print('kavinda')

kavinda


In [13]:
if '':
    print('If')
else:
    print('Else')

Else


In [14]:
import numpy as np 

In [24]:
r = np.random.randn()

if r > 0:
    outcome = 'positive'
else:
    outcome = 'negative'

print('The number is ' + outcome)

The number is negative


In [57]:
r = [ 1, 3, 7, 9]

def fun(r):
    if r == 1:
        print('r == 1')
    elif r < 5:
        print('r < 5')
    elif r < 9:
        print('r < 9')
    else:
        print('r == 9')

    print(r)

In [58]:
fun(r[0])
fun(r[1])
fun(r[2])
fun(r[3])

r == 1
1
r < 5
3
r < 9
7
r == 9
9


---
# ***If-else statements, part 2***
---

In [3]:
import numpy as np

In [19]:
x = np.random.randn()

if x > 0 : print('x is positive')
else : print('x is negative')

print('x is positive') if x > 0 else  print('x is negative')

x is positive
x is positive


In [22]:
'A'.lower(), 'a'.upper()

('a', 'A')

In [23]:
# conjunction conditionals

if 1<3 and 4==5:
    print('Both conditionals are True.')
else:
    print('At least one conditional is false.')

At least one conditional is false.


## Exercise

In [41]:
x = int(2)



False

In [75]:
def dot(v1, v2):
    if not ( isinstance(v1, np.ndarray) and isinstance(v2, np.ndarray) ):
        raise Exception('Inputs must be numpy arrays')
    elif not len(v1) == len(v2):
        raise Exception('v1 or v2 not have smae shape')
    
    return np.sum(v1*v2)

In [81]:
v1 = np.array([1, 2, 3])
v2 = np.array([1, 2, 3])
dot(v1, v2)

14

---
# ***For loops***
---

In [11]:
for i in range(3, 6):
    print(i, i**2)

3 9
4 16
5 25


In [8]:
import numpy as np

In [10]:
numbers = np.linspace(3, 17.1, 22)

In [15]:
for i in range(len(numbers)):
    print(numbers[i], end=', ')

3.0, 3.6714285714285717, 4.342857142857143, 5.014285714285714, 5.685714285714286, 6.357142857142858, 7.0285714285714285, 7.7, 8.371428571428572, 9.042857142857144, 9.714285714285715, 10.385714285714286, 11.057142857142857, 11.72857142857143, 12.4, 13.071428571428573, 13.742857142857144, 14.414285714285715, 15.085714285714287, 15.757142857142858, 16.42857142857143, 17.1, 

In [17]:
for i in numbers:
    print(i, end=', ')

3.0, 3.6714285714285717, 4.342857142857143, 5.014285714285714, 5.685714285714286, 6.357142857142858, 7.0285714285714285, 7.7, 8.371428571428572, 9.042857142857144, 9.714285714285715, 10.385714285714286, 11.057142857142857, 11.72857142857143, 12.4, 13.071428571428573, 13.742857142857144, 14.414285714285715, 15.085714285714287, 15.757142857142858, 16.42857142857143, 17.1, 

In [18]:
for i in range(5):
    if i%2 == 0:
        print(f'{i} is even number.')
    else:
        print(f'{i} is odd number.')

0 is even number.
1 is odd number.
2 is even number.
3 is odd number.
4 is even number.


## Exercise

`fibonacci series : [0, 1, 1, 2, 3, ...] (some of previous two numbers)` 

In [39]:
def FibonacciSeries(i, n1=0, n2=1):
    series = [n1, n2]

    for i in range(i-2):
        series.append( sum(series[-2:]) )
    
    return series

In [40]:
FibonacciSeries(10)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

---
# ***Enumerate and zip***
---

In [41]:
import numpy as np

In [42]:
ns = np.linspace(-5, 5, 7)

In [46]:
for i, n in enumerate(ns):
    print(f'{i} : {n}')

0 : -5.0
1 : -3.333333333333333
2 : -1.6666666666666665
3 : 0.0
4 : 1.666666666666667
5 : 3.333333333333334
6 : 5.0


In [76]:
text = 'hello world'
vowels = np.zeros(len(text), np.int)

for i, l in enumerate(text):
    if l in 'aeiou': vowels[i] = 1 

vowels

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0])

In [83]:
listA = [1, 2, 3, 4]
listB = ['a', 'b', 'c', 'd']

In [84]:
for i in range(len(listA)):
    print(f'{listA[i]} : {listB[i]}')

1 : a
2 : b
3 : c
4 : d


In [85]:
for a,b in zip(listA, listB):
    print(f'{a} : {b}')

1 : a
2 : b
3 : c
4 : d


In [86]:
listA = [1, 2, 3, 4]
listB = ['a', 'b']

for a,b in zip(listA, listB):
    print(f'{a} : {b}')

1 : a
2 : b


## Exercise

In [100]:
names = ['alpha', 'beta', 'gamma']
values = [10, 20, 30]

In [101]:
D1 = dict()

for n, v in zip(names, values):
    D1[n] = v

D1

{'alpha': 10, 'beta': 20, 'gamma': 30}

In [102]:
D2 = dict(zip(names, values))
D2

{'alpha': 10, 'beta': 20, 'gamma': 30}

---
# ***Continue***
---

In [107]:
for i in range(10):
    if i%2 == 0 : continue
    print(i)

1
3
5
7
9


In [114]:
text = 'KaViNdA'

for l in text:
    if l.lower() in 'aeiou': continue
    print(l, end='')

KVNd

---
# ***Initializing variables***
---

In [1]:
import numpy as np

In [1]:
r = 10

In [2]:
whos

Variable   Type      Data/Info
------------------------------
os         module    <module 'os' from 'C:\\Us<...>\\anaconda3\\lib\\os.py'>
r          int       10
sys        module    <module 'sys' (built-in)>


In [3]:
# delete a variable
del r

In [4]:
whos

Variable   Type      Data/Info
------------------------------
os         module    <module 'os' from 'C:\\Us<...>\\anaconda3\\lib\\os.py'>
sys        module    <module 'sys' (built-in)>


In [5]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.full(10, 112)

array([112, 112, 112, 112, 112, 112, 112, 112, 112, 112])

In [16]:
N = 10

r = []

for i in range(N):
    r.append( i**2 )

print(r)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [19]:
N = 10

r = np.array([])

for i in range(N):
    r = np.append(r, i**2 )

print(r)

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [9]:
N = 10

r = np.zeros(N)

for i in range(N):
    r[i] = i**2

print(r)

[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]


In [15]:
r = np.zeros( shape=(2,3), dtype=np.complex )
r

array([[0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j]])

## Exercise

In [14]:
import time

In [15]:
tStart = 0
tStop = 0
N = 10000
t = [0]*3

In [16]:
tStart = time.perf_counter()

r = []

for i in range(N):
    r.append( i**2 )

tStop = time.perf_counter()

t[0] = tStop - tStart

In [17]:
tStart = time.perf_counter()

r = np.array([])

for i in range(N):
    r = np.append(r, i**2 )

tStop = time.perf_counter()

t[1] = tStop - tStart

In [18]:
tStart = time.perf_counter()

r = np.zeros(N)

for i in range(N):
    r[i] = i**2

tStop = time.perf_counter()

t[2] = tStop - tStart

In [19]:
print(f'List Append Time          : {1000*t[0]} ms')
print(f'Numpy Append Time         : {1000*t[1]} ms')
print(f'Numpy Initialization Time : {1000*t[2]} ms')

List Append Time          : 9.404799999970237 ms
Numpy Append Time         : 217.62780000000248 ms
Numpy Initialization Time : 8.911300000022493 ms


---
# ***Single-line loops (list comprehension)***
---

In [1]:
import random

In [5]:
random.randint(1,10)

4

In [27]:
r = random.randint(1,10)

print('r is large',r) if r>5 else print('r is small',r)

r is small 5


In [33]:
[ i**2 for i in range(10) ]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [36]:
[ i**2 for i in range(10) if i>5 ]

[36, 49, 64, 81]

In [72]:
x = 10

In [73]:
x

10

In [78]:
x; # ; suppress the output

## Exercise

In [79]:
text = ['Promising', 'Yves', 'That', 'Home', 'On', 'Nobb']

[ print(word[0], end='') for word in text ];

PYTHON

In [83]:
['odd' if i%2==1 else i for i in range(10)]

[0, 'odd', 2, 'odd', 4, 'odd', 6, 'odd', 8, 'odd']

In [48]:
import numpy as np

x1 = np.linspace(-3, 3, 11)
y1 = x1**2

x1, y1

(array([-3. , -2.4, -1.8, -1.2, -0.6,  0. ,  0.6,  1.2,  1.8,  2.4,  3. ]),
 array([9.  , 5.76, 3.24, 1.44, 0.36, 0.  , 0.36, 1.44, 3.24, 5.76, 9.  ]))

In [87]:
s = ( 3 - (-3)) / (11 - 1)

x1 =[ round(-3 + (i * s), 2) for i in range(11)]
x1

[-3.0, -2.4, -1.8, -1.2, -0.6, 0.0, 0.6, 1.2, 1.8, 2.4, 3.0]

In [90]:
[(i*3)/5 for i in range(-5, 6)]

[-3.0, -2.4, -1.8, -1.2, -0.6, 0.0, 0.6, 1.2, 1.8, 2.4, 3.0]

In [70]:
y1 = [i**2 for i in x1]
y1

[9.0, 5.76, 3.24, 1.44, 0.36, 0.0, 0.36, 1.44, 3.24, 5.76, 9.0]