---
# ***Inputs and outputs***
---

In [12]:
alist = [2, 4, 43, 31.12]
output =  sum(alist)

print('The sum is ' + str(output))

The sum is 80.12


## Exercise

In [14]:
alist = [1, 2, 3]

mean = sum(alist)/len(alist)
mean

2.0

---
# ***Python libraries (numpy)***
---

In [16]:
import numpy as np

In [17]:
numbers = [1, 2, 3]
np.mean(numbers)

2.0

In [20]:
x = np.linspace(1,7,5)
x, type(x)

(array([1. , 2.5, 4. , 5.5, 7. ]), numpy.ndarray)

In [22]:
numbers_np = np.array(numbers)
print(numbers_np)
type(numbers), type(numbers_np)

[1 2 3]


(list, numpy.ndarray)

In [24]:
numbers_np.mean(), numbers_np.min(), numbers_np.max()

(2.0, 1, 3)

In [25]:
np.mean(numbers_np), np.min(numbers_np), np.max(numbers_np)

(2.0, 1, 3)

In [26]:
np.mean(numbers), np.min(numbers), np.max(numbers)

(2.0, 1, 3)

In [28]:
from numpy import mean as npMena

npMena(numbers_np)

2.0

## `In-place`
## `out-of-place / not in-place operations`

### In-place oparation

In [30]:
n = [4, 1, 5, 2, 3]
nn = np.array(n)

print(nn)
nn.sort()
print(nn)

[4 1 5 2 3]
[1 2 3 4 5]


### Out-of-place / not in-place operations

In [31]:
n = [4, 1, 5, 2, 3]
nn = np.array(n)

print(nn)
np.sort(nn)
print(nn)

[4 1 5 2 3]
[4 1 5 2 3]


In [32]:
nns = np.sort(nn)

nns, nn

(array([1, 2, 3, 4, 5]), array([4, 1, 5, 2, 3]))

---
# ***Python libraries (pandas)***
---

In [2]:
import numpy as np
import pandas as pd

In [9]:
var1 = np.random.randn(100)*5 + 20
var2 = np.random.randn(100)>0

var1[:5], var2[:5]

(array([19.57753346, 13.74105499, 26.63292502, 20.67357816, 27.31901071]),
 array([False, False,  True,  True,  True]))

In [10]:
labels = ['Temp (C)', 'Ice cream']

In [11]:
D = { labels[0]: var1, labels[1]: var2}

In [19]:
df = pd.DataFrame(data=D)
df.head(3)

Temp (C)  Ice cream
0  19.577533      False
1  13.741055      False
2  26.632925       True

In [21]:
type(df)

(pandas.core.frame.DataFrame,
 Temp (C)     100
 Ice cream    100
 dtype: int64)

In [22]:
df.count()

Temp (C)     100
Ice cream    100
dtype: int64

In [23]:
df.mean()

Temp (C)     20.119027
Ice cream     0.450000
dtype: float64

## Exercise

In [38]:
numbers = np.arange(11)

df = pd.DataFrame(
    {
        'Numbers': numbers, 
        'Square': np.square(numbers), 
        'Log': np.log(numbers)
    }
)
df

<ipython-input-38-53583256d274>:7: RuntimeWarning: divide by zero encountered in log
  'Log': np.log(numbers)


Numbers  Square       Log
0         0       0      -inf
1         1       1  0.000000
2         2       4  0.693147
3         3       9  1.098612
4         4      16  1.386294
5         5      25  1.609438
6         6      36  1.791759
7         7      49  1.945910
8         8      64  2.079442
9         9      81  2.197225
10       10     100  2.302585