---
# ***Inputs and outputs***
---

In [50]:
alist = [2, 4, 43, 31.12]
output =  sum(alist)

print('The sum is ' + str(output))

The sum is 80.12


## Exercise

In [51]:
alist = [1, 2, 3]

mean = sum(alist)/len(alist)
mean

2.0

---
# ***Python libraries (numpy)***
---

In [52]:
import numpy as np

In [53]:
numbers = [1, 2, 3]
np.mean(numbers)

2.0

In [54]:
x = np.linspace(1,7,5)
x, type(x)

(array([1. , 2.5, 4. , 5.5, 7. ]), numpy.ndarray)

In [55]:
numbers_np = np.array(numbers)
print(numbers_np)
type(numbers), type(numbers_np)

[1 2 3]


(list, numpy.ndarray)

In [56]:
numbers_np.mean(), numbers_np.min(), numbers_np.max()

(2.0, 1, 3)

In [57]:
np.mean(numbers_np), np.min(numbers_np), np.max(numbers_np)

(2.0, 1, 3)

In [58]:
np.mean(numbers), np.min(numbers), np.max(numbers)

(2.0, 1, 3)

In [59]:
from numpy import mean as npMena

npMena(numbers_np)

2.0

## `In-place`
## `out-of-place / not in-place operations`

### In-place oparation

In [60]:
n = [4, 1, 5, 2, 3]
nn = np.array(n)

print(nn)
nn.sort()
print(nn)

[4 1 5 2 3]
[1 2 3 4 5]


### Out-of-place / not in-place operations

In [61]:
n = [4, 1, 5, 2, 3]
nn = np.array(n)

print(nn)
np.sort(nn)
print(nn)

[4 1 5 2 3]
[4 1 5 2 3]


In [62]:
nns = np.sort(nn)

nns, nn

(array([1, 2, 3, 4, 5]), array([4, 1, 5, 2, 3]))

---
# ***Python libraries (pandas)***
---

In [63]:
import numpy as np
import pandas as pd

In [64]:
var1 = np.random.randn(100)*5 + 20
var2 = np.random.randn(100)>0

var1[:5], var2[:5]

(array([28.17377756, 21.84632667, 22.62394154, 18.79948936, 22.83633276]),
 array([ True,  True,  True,  True,  True]))

In [65]:
labels = ['Temp (C)', 'Ice cream']

In [66]:
D = { labels[0]: var1, labels[1]: var2}

In [67]:
df = pd.DataFrame(data=D)
df.head(3)

Temp (C)  Ice cream
0  28.173778       True
1  21.846327       True
2  22.623942       True

In [68]:
type(df)

pandas.core.frame.DataFrame

In [69]:
df.count()

Temp (C)     100
Ice cream    100
dtype: int64

In [70]:
df.mean()

Temp (C)     20.648801
Ice cream     0.550000
dtype: float64

## Exercise

In [71]:
numbers = np.arange(11)

df = pd.DataFrame(
    {
        'Numbers': numbers, 
        'Square': np.square(numbers), 
        'Log': np.log(numbers)
    }
)
df

<ipython-input-71-53583256d274>:7: RuntimeWarning: divide by zero encountered in log
  'Log': np.log(numbers)


Numbers  Square       Log
0         0       0      -inf
1         1       1  0.000000
2         2       4  0.693147
3         3       9  1.098612
4         4      16  1.386294
5         5      25  1.609438
6         6      36  1.791759
7         7      49  1.945910
8         8      64  2.079442
9         9      81  2.197225
10       10     100  2.302585

---
# ***Getting help on functions***
---

In [72]:
x = [1, 2, 3]
sum(x), sum(x, start=10), sum(x)+10

(6, 16, 16)

In [73]:
sum?

Signature: sum(iterable, /, start=0)
Docstring:
Return the sum of a 'start' value (default: 0) plus an iterable of numbers

When the iterable is empty, return the start value.
This function is intended specifically for use with numeric values and may
reject non-numeric types.
Type:      builtin_function_or_method


In [74]:
# some times the source
sum??

Signature: sum(iterable, /, start=0)
Docstring:
Return the sum of a 'start' value (default: 0) plus an iterable of numbers

When the iterable is empty, return the start value.
This function is intended specifically for use with numeric values and may
reject non-numeric types.
Type:      builtin_function_or_method


In [75]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [76]:
import numpy as np

In [77]:
np.linspace?

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : 

In [78]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [79]:
np.linspace??

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Source:   
@array_function_dispatch(_linspace_dispatcher)
def linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,
             axis=0):
    """
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num

---
# ***Creating functions***
---

In [80]:
def myFunction():
    print('My function')

In [81]:
myFunction()

My function


In [82]:
fun = myFunction

In [83]:
fun()

My function


In [84]:
def myFunction(x, y):
    print(x + y)

In [85]:
myFunction(1, 2)

3


In [86]:
def myFunction(x, y):
    return x+y

In [87]:
ans = myFunction(12, 4)
ans

16

In [88]:
def myFunction(x, y):
    return x+y, x*y

In [89]:
ans = myFunction(10, 7)
ans, type(ans)

((17, 70), tuple)

In [90]:
s, p = myFunction(10, 7)

print(s, p)

17 70


## Lambda function

In [91]:
fun = lambda x: [i for i in range(x)]

fun(10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [92]:
fun = lambda x, y: x+y

fun(10, -12)

-2

## Exercise

In [97]:
def myFactorial(num):
    if num == 1:
        return 1
    return num*myFactorial(num - 1)

In [98]:
myFactorial(4), 1*2*3*4

(24, 24)

In [99]:
import numpy as np
from math import factorial

def myFactorial(num):
    arr = np.arange(1,num+1)
    return np.prod(arr)

myFactorial(4), factorial(4)

(24, 24)

---
# ***Global and local variable scopes***
---

In [100]:
%whos

Variable      Type                          Data/Info
-----------------------------------------------------
D             dict                          n=2
a             dict                          n=2
alist         list                          n=3
ans           tuple                         n=2
b             dict                          n=2
copy          module                        <module 'copy' from 'C:\\<...>anaconda3\\lib\\copy.py'>
deepcopy      function                      <function deepcopy at 0x000001FE79FBAAF0>
df            DataFrame                         Numbers  Square      <...>     10     100  2.302585
factorial     builtin_function_or_method    <built-in function factorial>
fun           function                      <function <lambda> at 0x000001FE009FF1F0>
labels        list                          n=2
mean          float                         2.0
myFactorial   function                      <function myFactorial at 0x000001FE009C5790>
myFunction    functio

In [101]:
def fun1():
    x = 7 # x is a local variable
    print(x)

y = 15 # z is a global variable

def fun2():
    global z 
    z = 234 # z is a global variable

fun1()
fun2() # Function need to call first for initialize as a global variable

7


In [102]:
y, z

(15, 234)

In [103]:
x = 125
fun1()

print(x)

7
125


In [104]:
def fun3():
    print(z)
    print(a)

a = 'hello'

fun3()

234
hello


## Exercise

In [105]:
from numpy.random import randint
from numpy.random import randn
from numpy import mean 

### My solution

In [106]:
def coinFlipAvg(n):
    avg = mean(randint(0, 2, size = n))
    return avg
    
print(f'Average : {coinFlipAvg(100)}')

Average : 0.48


### Course solution

In [107]:
def coinFlip(n):
    propCoinFlips = mean( randn(n)>0 )
    print(f'{n} coin flips, {100*propCoinFlips}% heads')

coinFlip(100)

100 coin flips, 49.0% heads


---
# ***Copies and referents of variables***
---

## Variable

In [1]:
a = 5
b = a # copy

a, b

(5, 5)

In [2]:
a = 74
a, b

(74, 5)

In [3]:
id(a), id(b), id(a) == id(b)

(140719007739968, 140719007737760, False)

## List

In [4]:
a = [1, 2, 3]
b = a # ref

a[0] = 123

id(a), id(b), id(a) == id(b)

(1515426210240, 1515426210240, True)

In [5]:
a = [1, 2, 3]
b = a # ref

b[0] = 77

id(a), id(b), id(a) == id(b)

(1515426269952, 1515426269952, True)

In [6]:
a = [1, 2, 3]
b = a[:] # copy

b[0] = 77

id(a), id(b), id(a) == id(b)

(1515426269632, 1515426270464, False)

## Dictionary

In [21]:
a = {'a': 1, 'b':2}
a = b # ref

id(a) == id(b)

True

In [1]:
a = {'a': [1, 2], 'b':2}
b = a.copy() # shallow copy

id(a) == id(b)

False

In [4]:
a['a'][0] = 123

a['a'][0], b['a'][0]

(123, 123)

In [5]:
import copy

a = {'a': [1, 2], 'b':2}
b = copy.deepcopy(a)

id(a) == id(b)

False

In [6]:
id(a['a'][0]) == id(b['a'][0])

True

In [9]:
a['a'][0] = 345
id(a['a'][0]) == id(b['a'][0])

False

In [10]:
a['a'][0], b['a'][0]

(345, 1)

---
# ***Classes and object-oriented programming***
---

In [35]:
#              _______ use for inheritance
#           __|___
class model(object):

    # constructor method
    #               ______ instance of the object
    #            __|_
    def __init__(self, numlayers, numunits, name):
        self.layers  = numlayers # attributes
        self.units   = numunits
        self.name    = name
        self.weights = 1
    
    def howManyUnits(self):
        totalUnits = self.layers * self.units
        print(f'There are {totalUnits} units in the model.')

    def trainTheModel(self, x):
        self.weights += x
        return self.weights

    def __str__(self):
        return f'This is a {self.name} architecture.'

In [36]:
m1 = model(2, 5, 'CNN')

In [37]:
m1.howManyUnits()

There are 10 units in the model.


In [38]:
m1.trainTheModel(2.5)

3.5

In [39]:
m1.trainTheModel(2.5)

6.0

In [40]:
str(m1)

'This is a CNN architecture.'

## Exercise

In [56]:
import numpy as np

class model(object):

    def __init__(self, numlayers, numunits, name):
        self.layers  = numlayers
        self.units   = numunits
        self.name    = name
        self.weights = np.random.randn(numlayers, numunits)
    
    def howManyUnits(self):
        totalUnits = self.layers * self.units
        print(f'There are {totalUnits} units in the model.')

    def trainTheModel(self, x, y):
        self.weights = self.weights*x + y

    def __str__(self):
        return f'This is a {self.name} architecture.'

In [57]:
m1 = model(2, 5, 'X')
m1.weights

array([[-1.34416877,  0.15893594, -0.94811274, -0.37383976,  0.39966982],
       [ 0.39216716, -0.54747145,  0.73817195, -0.82981302,  0.15060386]])

In [58]:
m1.trainTheModel(2,3)
m1.weights

array([[0.31166246, 3.31787188, 1.10377452, 2.25232047, 3.79933964],
       [3.78433432, 1.9050571 , 4.47634389, 1.34037396, 3.30120773]])

In [59]:
m1.trainTheModel(2,3)
m1.weights

array([[ 3.62332492,  9.63574377,  5.20754905,  7.50464094, 10.59867927],
       [10.56866865,  6.81011421, 11.95268778,  5.68074792,  9.60241546]])