---
# ***Inputs and outputs***
---

In [12]:
alist = [2, 4, 43, 31.12]
output =  sum(alist)

print('The sum is ' + str(output))

The sum is 80.12


## Exercise

In [14]:
alist = [1, 2, 3]

mean = sum(alist)/len(alist)
mean

2.0

---
# ***Python libraries (numpy)***
---

In [16]:
import numpy as np

In [17]:
numbers = [1, 2, 3]
np.mean(numbers)

2.0

In [20]:
x = np.linspace(1,7,5)
x, type(x)

(array([1. , 2.5, 4. , 5.5, 7. ]), numpy.ndarray)

In [22]:
numbers_np = np.array(numbers)
print(numbers_np)
type(numbers), type(numbers_np)

[1 2 3]


(list, numpy.ndarray)

In [24]:
numbers_np.mean(), numbers_np.min(), numbers_np.max()

(2.0, 1, 3)

In [25]:
np.mean(numbers_np), np.min(numbers_np), np.max(numbers_np)

(2.0, 1, 3)

In [26]:
np.mean(numbers), np.min(numbers), np.max(numbers)

(2.0, 1, 3)

In [28]:
from numpy import mean as npMena

npMena(numbers_np)

2.0

## `In-place`
## `out-of-place / not in-place operations`

### In-place oparation

In [30]:
n = [4, 1, 5, 2, 3]
nn = np.array(n)

print(nn)
nn.sort()
print(nn)

[4 1 5 2 3]
[1 2 3 4 5]


### Out-of-place / not in-place operations

In [31]:
n = [4, 1, 5, 2, 3]
nn = np.array(n)

print(nn)
np.sort(nn)
print(nn)

[4 1 5 2 3]
[4 1 5 2 3]


In [32]:
nns = np.sort(nn)

nns, nn

(array([1, 2, 3, 4, 5]), array([4, 1, 5, 2, 3]))