---
# ***Inputs and outputs***
---

In [12]:
alist = [2, 4, 43, 31.12]
output =  sum(alist)

print('The sum is ' + str(output))

The sum is 80.12


## Exercise

In [14]:
alist = [1, 2, 3]

mean = sum(alist)/len(alist)
mean

2.0

---
# ***Python libraries (numpy)***
---

In [16]:
import numpy as np

In [17]:
numbers = [1, 2, 3]
np.mean(numbers)

2.0

In [20]:
x = np.linspace(1,7,5)
x, type(x)

(array([1. , 2.5, 4. , 5.5, 7. ]), numpy.ndarray)

In [22]:
numbers_np = np.array(numbers)
print(numbers_np)
type(numbers), type(numbers_np)

[1 2 3]


(list, numpy.ndarray)

In [24]:
numbers_np.mean(), numbers_np.min(), numbers_np.max()

(2.0, 1, 3)

In [25]:
np.mean(numbers_np), np.min(numbers_np), np.max(numbers_np)

(2.0, 1, 3)

In [26]:
np.mean(numbers), np.min(numbers), np.max(numbers)

(2.0, 1, 3)

In [28]:
from numpy import mean as npMena

npMena(numbers_np)

2.0

## `In-place`
## `out-of-place / not in-place operations`

### In-place oparation

In [30]:
n = [4, 1, 5, 2, 3]
nn = np.array(n)

print(nn)
nn.sort()
print(nn)

[4 1 5 2 3]
[1 2 3 4 5]


### Out-of-place / not in-place operations

In [31]:
n = [4, 1, 5, 2, 3]
nn = np.array(n)

print(nn)
np.sort(nn)
print(nn)

[4 1 5 2 3]
[4 1 5 2 3]


In [32]:
nns = np.sort(nn)

nns, nn

(array([1, 2, 3, 4, 5]), array([4, 1, 5, 2, 3]))

---
# ***Python libraries (pandas)***
---

In [2]:
import numpy as np
import pandas as pd

In [9]:
var1 = np.random.randn(100)*5 + 20
var2 = np.random.randn(100)>0

var1[:5], var2[:5]

(array([19.57753346, 13.74105499, 26.63292502, 20.67357816, 27.31901071]),
 array([False, False,  True,  True,  True]))

In [10]:
labels = ['Temp (C)', 'Ice cream']

In [11]:
D = { labels[0]: var1, labels[1]: var2}

In [19]:
df = pd.DataFrame(data=D)
df.head(3)

Temp (C)  Ice cream
0  19.577533      False
1  13.741055      False
2  26.632925       True

In [21]:
type(df)

(pandas.core.frame.DataFrame,
 Temp (C)     100
 Ice cream    100
 dtype: int64)

In [22]:
df.count()

Temp (C)     100
Ice cream    100
dtype: int64

In [23]:
df.mean()

Temp (C)     20.119027
Ice cream     0.450000
dtype: float64

## Exercise

In [38]:
numbers = np.arange(11)

df = pd.DataFrame(
    {
        'Numbers': numbers, 
        'Square': np.square(numbers), 
        'Log': np.log(numbers)
    }
)
df

<ipython-input-38-53583256d274>:7: RuntimeWarning: divide by zero encountered in log
  'Log': np.log(numbers)


Numbers  Square       Log
0         0       0      -inf
1         1       1  0.000000
2         2       4  0.693147
3         3       9  1.098612
4         4      16  1.386294
5         5      25  1.609438
6         6      36  1.791759
7         7      49  1.945910
8         8      64  2.079442
9         9      81  2.197225
10       10     100  2.302585

---
# ***Getting help on functions***
---

In [5]:
x = [1, 2, 3]
sum(x), sum(x, start=10), sum(x)+10

(6, 16, 16)

In [7]:
sum?

Signature: sum(iterable, /, start=0)
Docstring:
Return the sum of a 'start' value (default: 0) plus an iterable of numbers

When the iterable is empty, return the start value.
This function is intended specifically for use with numeric values and may
reject non-numeric types.
Type:      builtin_function_or_method


In [16]:
# some times the source
sum??

Signature: sum(iterable, /, start=0)
Docstring:
Return the sum of a 'start' value (default: 0) plus an iterable of numbers

When the iterable is empty, return the start value.
This function is intended specifically for use with numeric values and may
reject non-numeric types.
Type:      builtin_function_or_method


In [13]:
help(sum)

Help on built-in function sum in module builtins:

sum(iterable, /, start=0)
    Return the sum of a 'start' value (default: 0) plus an iterable of numbers
    
    When the iterable is empty, return the start value.
    This function is intended specifically for use with numeric values and may
    reject non-numeric types.



In [17]:
import numpy as np

In [18]:
np.linspace?

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : 

In [20]:
help(np.linspace)

Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num : int, optional
        Number of samples to generate. Default is 50. Must be non-negative.
    endpoint : bool, optional
        If True, `stop` is

In [19]:
np.linspace??

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Source:   
@array_function_dispatch(_linspace_dispatcher)
def linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,
             axis=0):
    """
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that `stop` is excluded.  Note that the step
        size changes when `endpoint` is False.
    num

---
# ***Creating functions***
---

In [32]:
def myFunction():
    print('My function')

In [33]:
myFunction()

My function


In [34]:
fun = myFunction

In [35]:
fun()

My function


In [36]:
def myFunction(x, y):
    print(x + y)

In [37]:
myFunction(1, 2)

3


In [38]:
def myFunction(x, y):
    return x+y

In [39]:
ans = myFunction(12, 4)
ans

16

In [40]:
def myFunction(x, y):
    return x+y, x*y

In [41]:
ans = myFunction(10, 7)
ans, type(ans)

((17, 70), tuple)

In [42]:
s, p = myFunction(10, 7)

print(s, p)

17 70


## Lambda function

In [44]:
fun = lambda x: [i for i in range(x)]

fun(10)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [45]:
fun = lambda x, y: x+y

fun(10, -12)

-2

## Exercise

In [2]:
def myFactorial(num):
    if num == 1:
        return 1
    return num*factorial(num - 1)

In [3]:
myFactorial(4), 1*2*3*4

(24, 24)

In [4]:
import numpy as np
from math import factorial

def myFactorial(num):
    arr = np.arange(1,num+1)
    return np.prod(arr)

myFactorial(4), factorial(4)

(24, 24)