In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [10]:
prob = 0.5

dropout = nn.Dropout(p=prob)
x = torch.ones(10)
val = 1

y = dropout(x)
print(x)
print(y)
print(val * (1/(1-prob)))
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([2., 2., 0., 0., 0., 2., 0., 2., 2., 2.])
2.0
tensor(1.2000)


In [4]:
dropout.eval()

y = dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [11]:
y = F.dropout(x)
print(y)
print(torch.mean(y))

tensor([0., 0., 0., 0., 2., 0., 0., 2., 0., 0.])
tensor(0.4000)


In [12]:
y = F.dropout(x, training=False)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [13]:
dropout.train()
y = dropout(x)
print(y)

dropout.eval()
y = dropout(x)
print(y)

tensor([2., 0., 0., 0., 2., 0., 0., 2., 2., 2.])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
